[general]
import = [
    # "~/.config/alacritty/themes/themes/catppuccin.toml"
    # "~/.config/alacritty/themes/themes/dracula_plus.toml"
    # "~/.config/alacritty/themes/themes/iterm.toml"
    # "~/.config/alacritty/themes/themes/night_owl.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
    # "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
    # "~/.config/alacritty/themes/themes/seashells.toml"
    # "~/.config/alacritty/themes/themes/catppuccin.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[terminal]
shell = "fish"

[window]
dynamic_padding = true
decorations = "Full"
opacity = 1.0

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }

size = 13
